language_map:
  two_letters_code:
    en-PT: en-PT
    en-pt: en-PT

files:
  - source: /messages/en.json
    translation: /messages/%two_letters_code%.json
    translatable_elements:
      - "match.*"
    type: i18next_json